name: Run vader tests

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        vim_type: ['vim', 'neovim']
        vim_version: ['head', 'stable']
        os: ['ubuntu-latest', 'windows-latest']
        include:
          - vim_type: 'vim'
            version: 'v8.0.0000'
          #- vim_type: 'vim'
          #  version: 'stable'
          #  vim_version: 'v7.4'
          #- vim_type: 'vim'
          #  version: 'stable'
          #  vim_version: 'v7.0'
          - vim_type: 'neovim'
            vim_version: 'stable'
            version: 'v0.4.4'
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Setup vim/neovim'
        id: 'vim'
        uses: 'thinca/action-setup-vim@v1'
        with:
          vim_version: '${{ matrix.version || matrix.vim_version }}'
          vim_type: '${{ matrix.vim_type }}'
      - name: 'Install vader.vim'
        run: git clone https://github.com/junegunn/vader.vim.git
      - name: 'Run vader tests'
        env:
          TESTVIM: ${{ steps.vim.outputs.executable }}
        shell: bash
        run: ./tests/run_tests.sh
