name: Run vader tests

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  test:
    strategy:
      matrix:
        vim_type: ['vim']
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        vim_version: ['head', 'v8.0.0000', 'v7.4', 'v7.0']
        exclude:
          # Build fails to find Quickdraw.h
          - os: 'macos-latest'
            vim_version: 'v7.0'
          # uint32_t is not correctly defined via configure
          - os: 'macos-latest'
            vim_version: 'v7.4'
          # Build causes a buffer overflow when running the test script
          - os: 'ubuntu-latest'
            vim_version: 'v7.0'
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Setup vim/neovim'
        id: 'vim'
        uses: 'thinca/action-setup-vim@v1'
        with:
          vim_version: '${{ matrix.version || matrix.vim_version }}'
          vim_type: '${{ matrix.vim_type }}'
      - name: 'Install vader.vim'
        run: git clone https://github.com/junegunn/vader.vim.git
      - name: 'Run vader tests'
        env:
          TESTVIM: ${{ steps.vim.outputs.executable }}
        shell: bash
        run: ./tests/run_tests.sh
