name: Run vader tests

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        vim_type: ['vim', 'neovim']
        os: ['ubuntu-latest', 'windows-latest']
        vim_version:
          #- 'v8.2.1000'
          #- 'v8.2.0000'
          #- 'v8.1.0000'
          - 'v8.0.0000'
          - 'v7.4'
          - 'v7.0'
          - 'v0.4.4'
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Setup vim/neovim'
        id: 'vim'
        uses: 'thinca/action-setup-vim@v1'
        with:
          vim_version: '${{ matrix.vim_version || matrix.version }}'
          vim_type: '${{ matrix.vim_type }}'
      - name: 'Install vader.vim'
        run: git clone https://github.com/junegunn/vader.vim.git
      - name: 'Run vader tests'
        env:
          TESTVIM: ${{ steps.vim.outputs.executable }}
        shell: bash
        run: ./tests/run_tests.sh
